name: CI - Coin Service

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Simular Error 3: Falta de dependencia (descomenta para probar)
      - name: Skip commons install (provoca error)
        run: echo "Skipping commons install on purpose"

      # Compilar commons
      - name: Build commons module
        run: mvn clean install -pl microservices/commons -am

      # Error 2: Linter Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # Compilar coin-service
      - name: Compile coin-service
        run: mvn clean compile -pl microservices/coin-service -am

      # Error 1: Test que falla
      - name: Run tests
        run: mvn test -pl microservices/coin-service -am


      - name: Run tests with coverage
        run: mvn clean verify -Pcoverage

